### ISSUE TITLE
exception error: no function clause matching gleam_pgo_ffi:convert_errorr(none_available)

### ISSUE THREAD

**Issue by megapctr** [gleam-experiments/pgo#10]
I couldn't get gleam_pgo to run any query, it would always crash with this error. You can reproduce it by running this project: https://github.com/megapctr/pgo_crash

**Comment by lpil** [comment]
Thank you for the reproduction, that's super useful 💜

**Comment by megapctr** [comment]
the crash seems to occur when there is a connection problem. I also noticed that I can't get a password-protected connection to initialize properly

**Comment by lpil** [comment]
Fixed this with a new error variant, thank you.
